#!/usr/bin/env bash
# Adapted from https://github.com/pyenv/pyenv-installer/
# Usage: curl https://raw.githubusercontent.com/BioDynaMo/biodynamo/master/util/install | bash

set -e

if [ -z ${BDM_INSTALL} ]; then
```cpp
#include <cmath>
#include <vector>
#include <memory>
#include <algorithm>
#include <omp.h>

namespace biodynamo {

class Cell {
public:
    double concentration;
    double volume;
    double growth_rate;
    
    Cell() : concentration(0.0), volume(1.0), growth_rate(0.0) {}
    
    void UpdateConcentration(double dt) {
        #pragma omp atomic
        concentration += growth_rate * dt;
    }
    
    void SetGrowthRate(double rate) {
        growth_rate = rate;
    }
};

class Environment {
private:
    std::vector<std::unique_ptr<Cell>> cells_;
    double diffusion_coefficient_;
    
public:
    Environment(double diff_coeff) : diffusion_coefficient_(diff_coeff) {}
    
    void AddCell(std::unique_ptr<Cell> cell) {
        cells_.push_back(std::move(cell));
    }
    
    void SimulateDiffusion(double dt) {
        #pragma omp parallel for
        for (size_t i = 0; i < cells_.size(); ++i) {
            double local_concentration = cells_[i]->concentration;
            double neighbor_avg = 0.0;
            int neighbor_count = 0;
            
            for (size_t j = 0; j < cells_.size(); ++j) {
                if (i != j) {
                    neighbor_avg += cells_[j]->concentration;
                    neighbor_count++;
                }
            }
            
            if (neighbor_count > 0) {
                neighbor_avg /= neighbor_count;
                double flux = diffusion_coefficient_ * (neighbor_avg - local_concentration);
                #pragma omp atomic
                cells_[i]->concentration += flux * dt;
            }
        }
    }
    
    void RunSolver(double total_time, double dt) {
        double current_time = 0.0;
        while (current_time < total_time) {
            double adaptive_dt = std::min(dt, total_time - current_time);
            
            #pragma omp parallel sections
            {
                #pragma omp section
                {
                    for (auto& cell : cells_) {
                        cell->UpdateConcentration(adaptive_dt);
                    }
                }
                
                #pragma omp section
                {
                    SimulateDiffusion(adaptive_dt);
                }
            }
            
            current_time += adaptive_dt;
        }
    }
    
    const std::vector<std::unique_ptr<Cell>>& GetCells() const {
        return cells_;
    }
};

} // namespace biodynamo
```
fi
echo "BDM_INSTALL is set to: $BDM_INSTALL"

temp_dir=$(mktemp -d)
BDM_SRC="${temp_dir}/biodynamo"
mkdir "$BDM_SRC"
cd $BDM_SRC

Colorize() {
  if [ -t 1 ]; then printf "\e[%sm%s\e[m" "$1" "$2"
  else echo -n "$2"
  fi
}

FailedClone() {
  Colorize 1 "ERROR"
  echo "Failed to git clone $1"
  exit -1
}

FailedCheckout() {
  Colorize 1 "ERROR"
  echo "Failed to git checkout $1"
  exit -1
}

Checkout() {
  # In Github Actions we checkout the branch that is running the install script
  REPO_URL="${GITHUB}/${GHA_REPOSITORY}.git"
  if [ ! -z ${GITHUB_ACTIONS+x} ]; then
    git clone --branch ${GHA_BRANCH_NAME} "$REPO_URL" . || FailedClone "$REPO_URL"
  else
    git clone "$1" . || FailedClone "$1"
    git checkout "$BDM_INSTALL" || FailedCheckout "$BDM_INSTALL"
  fi
}

# Check if git is installed
if ! command -v git 1>/dev/null 2>&1; then
  Colorize 1 "ERROR"
  echo "Git is not installed, can't continue." >&2
  exit 1
fi

if [ -n "${USE_GIT_URI}" ]; then
  GITHUB="git://github.com"
else
  GITHUB="https://github.com"
fi

# Clone BioDynaMo
Checkout "${GITHUB}/BioDynaMo/biodynamo.git"

# SBML is currently not supported anywhere
# See: https://trello.com/c/vKPbh4iG
SBML="-Dsbml=OFF"

# Log the installation process and print error message upon failure
log=${BDM_SRC}/installation.log
touch log
out_msg="Something went wrong with the installation. For more details check \
  the log file: \"${log}\""
trap "echo $out_msg" ERR

# Manifest exit code of command that is piped to tee
set -o pipefail

# In Github Actions we run the notebooks in a separate step
if [ ! -z ${GITHUB_ACTIONS+x} ]; then
  BDM_NOTEBOOKS="-Dnotebooks=off"
else
  BDM_NOTEBOOKS="-Dnotebooks=on"
fi

pwd
# Run ./install.sh
BDM_CMAKE_FLAGS="-Dtest=off $BDM_NOTEBOOKS $SBML ${BDM_CMAKE_FLAGS}" ./install.sh 2>&1 | tee "$log"

set +o pipefail
