name: Ubuntu CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev gcc-11 g++-11 libomp5 libomp-dev libnuma-dev freeglut3-dev \
          libreadline-dev libsqlite3-dev tk-dev ${{ env.PYOPENSSL }} ninja-build libblas-dev liblapack-dev libgit2-dev \
          libboost-dev
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.19.3/cmake-3.19.3-Linux-x86_64.sh
        chmod +x cmake-3.19.3-Linux-x86_64.sh
        sudo ./cmake-3.19.3-Linux-x86_64.sh --skip-license --prefix=/usr/local
    - name: Configure and build
      run: |
        mkdir build && cd build
        cmake .. -Dboost=ON
        make -j$(nproc)